- name: Hello Ansible
  hosts: localvm
  vars:
    user: "{{ ansible_ssh_user }}"
  sudo: yes
    
    
  tasks:
    - name: Hello server
      shell: date > now.txt
      
    - name: add ssh keys from public_key directory
      authorized_key: user={{user}} key="{{item}}" state=present
      with_items:
        - https://github.com/rdhyee.keys
        - https://github.com/eshellman.keys
      sudo: yes