- name: Hello Ansible
  hosts: localvm
  vars:
    user: "{{ ansible_ssh_user }}"
  sudo: yes
        
  pre_tasks:
    - name: Hello server
      shell: date > now.txt
  
  roles:
    - role: mysql

