    - name: mysql setup
      raw: debconf-set-selections <<< 'mysql-server-5.5 mysql-server/root_password password {{mysql_root_pw}}'
    - raw: debconf-set-selections <<< 'mysql-server-5.5 mysql-server/root_password_again password {{mysql_root_pw}}'
    - raw: apt-get -y install mysql-server
    
    - name: Create regluit database
      mysql_db: db=regluit state=present encoding=utf8 collation=utf8_bin login_user=root login_password={{mysql_root_pw}}
      
      # GRANT ALL PRIVILEGES ON regluit.* TO 'regluit'@'localhost' WITH GRANT OPTION; (covered?)
    - name: Create database user
      mysql_user: >
          user=regluit
          password={{mysql_regluit_pw}}
          host=localhost
          priv=*.*:ALL
          state=present
          login_user=root
          login_password={{mysql_root_pw}}