    # sudo add repo to get latest version of python 2.7
    - name: add-apt-repository ppa:fkrull/deadsnakes-python2.7
      apt_repository: repo='ppa:fkrull/deadsnakes-python2.7' state=present update_cache=true

    - name: do apt-get update --fix-missing
      command: apt-get update --fix-missing
      
    - name: installing dependencies
      apt: pkg={{ item }} update_cache=yes state=present
      with_items:
        - python2.7
        - git-core
        - apache2
        - libapache2-mod-wsgi
        - mysql-client
        - python-virtualenv
        - python-mysqldb
        - redis-server
        - python-lxml
        - python-dev
        - libjpeg-dev
        - libmysqlclient-dev
        - libxml2-dev
        - libxslt1-dev
        - python-setuptools
        - postfix
      tags: install
      
    - name: make {{user}} group
      group: name={{user}}
      
    - name: make {{user}} user 
      user: name={{user}} shell=/bin/bash group={{user}} generate_ssh_key=yes
      
    - name: install some python modules to use
      #pip: name={{item}} virtualenv=/home/{{user}}/venv
      pip: name={{item}}
      with_items:
        - PyGithub
      
    - name: create /opt/regluit
      file: path=/opt/regluit state=directory owner={{user}} group={{user}} mode=0745
    
    - name: git config
      command: "{{item}}"
      with_items:
        - git config --global user.name "Raymond Yee"
        - git config --global user.email "rdhyee@gluejar.com"
 
    - name: ssh-keygen
      #command: pwd
      command: ssh-keygen -b 2048 -t rsa -f /home/{{user}}/.ssh/id_rsa -P ""
      sudo: no
      args:
        creates: /home/{{user}}/.ssh/id_rsa
 
    - name: create deploy key for repo
      action: github_deploy_key
      sudo: no
      args:
        github_auth_key: "{{github_auth_key}}"
        repo_name: Gluejar/regluit
        key_name: localvm
        key_path: /home/{{user}}/.ssh/id_rsa.pub
 
    - name: postfix install
      raw: DEBIAN_FRONTEND='noninteractive' apt-get install -y -q --force-yes postfix
      
    - name: clone the regluit git repo into /opt/regluit
      sudo: no
      git: repo=ssh://git@github.com/Gluejar/regluit.git dest=/opt/regluit accept_hostkey=True force=yes version=sysadmin
    